#!/usr/bin/env python3
"""Build the client-side search index for the Koyo docs site.

Scans every HTML page under docs/ and writes docs/search-index.js defining
window.KOYO_SEARCH_INDEX. Run by hand after editing page content:

    python3 tools/build_search_index.py

Uses only the Python standard library.
"""
from __future__ import annotations

import re
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUTPUT = DOCS / "search-index.js"

TITLE_SUFFIX = " | Koyo Docs"


class Collector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.page = ""
        self.title = ""
        self.lede = ""
        self.entries = []
        self.section = ""
        self.section_title = ""
        self.section_body = []
        self.pending_section = None
        self.in_h1 = 0
        self.in_h2 = 0
        self.in_article = 0
        self.p_count = 0
        self.h1_parts = []
        self.h2_parts = []

    @staticmethod
    def clean(text: str) -> str:
        return re.sub(r"\s+", " ", text).strip()

    @property
    def collecting_section_body(self) -> bool:
        return bool(self.section and not self.in_h2)

    def handle_starttag(self, tag: str, attrs) -> None:
        mapping = dict(attrs)
        if tag == "article":
            self.in_article += 1
        elif tag == "h1":
            self.in_h1 += 1
        elif tag == "section" and self.in_article:
            self.pending_section = mapping.get("id", "")
        elif tag == "h2" and self.in_article:
            self.in_h2 += 1
        elif tag == "p" and self.in_article:
            self.p_count += 1

    def handle_endtag(self, tag: str) -> None:
        if tag == "article":
            self.in_article -= 1
        elif tag == "h1":
            if self.in_h1:
                self.in_h1 -= 1
            if not self.title:
                self.title = self.clean("".join(self.h1_parts))
            self.h1_parts = []
        elif tag == "h2":
            if self.in_h2:
                self.in_h2 -= 1
            if self.section:
                title = self.clean("".join(self.h2_parts))
                self.section_title = title
            self.h2_parts = []
        elif tag == "section" and self.in_article:
            if self.section:
                body = self.clean(" ".join(self.section_body))
                excerpt = body[:180]
                self.entries.append(
                    {
                        "page": self.page,
                        "id": self.section,
                        "title": self.title,
                        "section": self.section_title,
                        "excerpt": excerpt,
                        "body": body[:700],
                    }
                )
                self.section = ""
                self.section_title = ""
                self.section_body = []
            elif self.pending_section:
                self.section = self.pending_section
                self.pending_section = None

    def handle_data(self, data: str) -> None:
        if self.in_h1:
            self.h1_parts.append(data)
        elif self.in_h2 and self.section:
            self.h2_parts.append(data)
        elif self.collecting_section_body:
            self.section_body.append(data)
        elif self.in_article and self.p_count == 1 and not self.section:
            self.lede += data
        if self.title and self.section and not self.section_title:
            pass


def build_page(path: Path) -> dict:
    collector = Collector()
    collector.page = path.stem
    collector.feed(path.read_text(encoding="utf-8"))

    title = collector.title or path.stem
    if collector.page == "index":
        title = "Overview"
    try:
        title = title.replace(TITLE_SUFFIX, "").strip()
    except Exception:
        pass

    page_entry = {
        "page": collector.page,
        "id": "",
        "title": title,
        "section": "",
        "excerpt": collector.clean(collector.lede or title)[:200],
        "body": collector.clean(collector.lede or title)[:700],
    }

    entries = [page_entry] + collector.entries
    # Drop empty section entries (a section whose heading never resolved).
    entries = [e for e in entries if e["title"] and (e["excerpt"] or e["section"])]
    return {"page": collector.page, "entries": entries}


def main() -> int:
    pages = sorted(DOCS.glob("*.html"))
    if not pages:
        print("No HTML pages found in", DOCS)
        return 1

    all_entries = []
    for page in pages:
        info = build_page(page)
        all_entries.extend(info["entries"])
        print(f"indexed {info['page']}: {len(info['entries'])} entries")

    lines = [
        "// Generated by tools/build_search_index.py. Do not edit by hand.",
        "// Regenerate after changing page content:",
        "//   python3 tools/build_search_index.py",
        "window.KOYO_SEARCH_INDEX =",
    ]
    body = "[\n" + ",\n".join(
        "  " + json_dumps(e) for e in all_entries
    ) + "\n];\n"
    text = "\n".join(lines) + "\n" + body

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {len(all_entries)} entries to {OUTPUT}")
    return 0


def json_dumps(entry: dict) -> str:
    def esc(value: str) -> str:
        value = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", " ")
            .replace("\r", " ")
            .replace("\t", " ")
        )
        return '"' + value + '"'

    parts = []
    for key in ("page", "id", "title", "section", "excerpt", "body"):
        parts.append(f'"{key}": {esc(entry.get(key, ""))}')
    return "{" + ", ".join(parts) + "}"


if __name__ == "__main__":
    sys.exit(main())